function res = compareConfig(c1,c2)
% true if c1 and c2 correspond to the same calculation

% TODO: Extend this to compare all variables that define the calculation

if (c1.type ~= c2.type)
   res = false;
else
   % Compares that apply for all calc types;
   res = (c1.nangles == c2.nangles) ...
      && (c1.tstep == c2.tstep)...
      && (c1.nSave == c2.nSave)...
      && (c1.temp == c2.temp)...
      && (c1.x == c2.x)...
      && (c1.I == c2.I)...
      && (c1.beta1 == c2.beta1);
   if (c1.type == 0)
       res = res && (c1.nsteps == c2.nsteps);
   end
   if (c1.type == 1)
      res = res && (c1.V == c2.V)...
       && (c1.nsteps == c2.nsteps);
   end
   if (c2.type == 2)
      res = res && (c1.V1 == c2.V1) ...
         && (c1.V2 == c2.V2)...
         && (c1.n1 == c2.n1)...
         && (c1.n2 == c2.n2);
   end
   if (c2.type == 3)
      res = res && (c1.V == c2.V) ...
         && (c1.beta == c2.beta) ...
         && (c1.n1 == c2.n1) ...
         && (c1.n2 == c2.n2);
   end
end